---
language: python:3.6
services:
  - docker

os: linux
dist: xenial
sudo: enabled

branches:
  only:
    - master
    - devel
    - test

env:
  global:
    - ROLE_NAME: ansible-create-user
  matrix:
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: linuxmintd/mint19-amd64
    - MOLECULE_DISTRO: archlinux/base

install:
  - pip install --user --upgrade pip
  - pip install --user -r requirements.txt

script:
  - molecule test -s test-ci

after_sucess:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: never
    on_failure: always
