---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Print role name
      debug:
        msg: "Applying role ansible-create-user"
        verbosity: "{{ debug_verbosity_test }}"
      changed_when: false
  roles:
    - role: ansible-create-user
